version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.97.1"
    
phases:
  install:
    commands:
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd -
      - git submodule init
      - git submodule update
      - rm -rf /tmp/*
  build:
    commands:
      - echo "Starting build phase..."
      - pwd
      - ls -la
      - echo "Removing existing public directory..."
      - rm -rf public
      - echo "Running Hugo..."
      - hugo
      - echo "Syncing with S3..."
      - aws s3 sync public/ s3://hugo-final-project/ --region us-east-1 --delete
      - echo "Build phase completed."

  post_build:
    commands:
      - echo Build completed on `date`
