baseURL = "http://hugo-final-project.s3-website-us-east-1.amazonaws.com/" # Public IP of your EC2 instance
languageCode = "en-us" # Language
title = "Hugo AWS CD" # Title of your site
theme = "PaperMod" # The theme you are using
paginate = 5 # Items per page in lists

[[deployment.targets]]
name = "awsbucket"
URL = "s3://hugo-final-project/?region=us-east-1"
